name = "VQC"
uuid = "4e7ef24d-5ce9-45cd-92f9-e75ce747de94"
authors = ["supremacyfuture <support@supremacyfuture.com>"]
version = "0.1.0"

[compat]
julia = "1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
